### ISSUE TITLE
I couldn't restart the server using C# upcloud API

### ISSUE THREAD

**Issue by RajuSPR** [UpCloudLtd/upcloud-c-sharp-api#4]
I'm able to start the server through my application using upcloud C# API. But I couldn't restart the server.

I'm facing the following issue "{\n \"error\" : {\n \"error_code\" : \"TIMEOUT_MISSING\",\n \"error_message\" : \"The required attribute timeout is missing.\"\n }\n}\n". 

How can I fix this issue? 

Do you help me?

![image](https://user-images.githubusercontent.com/48589501/54428194-b618c100-4742-11e9-8cac-62dacd05c140.png)

**Comment by Darep** [comment]
Sorry for the late reply! Restart is by default a "soft" restart, and a soft restart requires "timeout" and "timeoutAction" parameters. These parameters specify what happens if the soft restart times out. Could you try adding those to your RestartServer object?

You can find more info about "timeout" and "timeoutAction" here: https://developers.upcloud.com/8-servers/#restart-server

**Comment by RajuSPR** [comment]
Initially, I'm facing the authorization required issue. But, In these API had mentioned that was no need for authorization to restart. As the screenshot is displayed below.

![image](https://user-images.githubusercontent.com/48589501/54514179-74c12500-497f-11e9-920d-e1de212d96c3.png)

After, I gave the authorization as stated below.

![image](https://user-images.githubusercontent.com/48589501/54516177-337f4400-4984-11e9-9c12-c1529b03a7d4.png)

Thereafter, I had to face the timeout issue. Here do I want to say one thing. 

A restart can be done in three ways:

1. by hard stopping, or,
2. by soft stopping with a timeout, or,
3. by soft stopping without a timeout. 

I had followed the third way. But this way also requires a timeout attribute. Below screenshot also attached.

![image](https://user-images.githubusercontent.com/48589501/54516772-e8663080-4985-11e9-981d-10f584c8c5ea.png)


How to fix this issue? Please anyone help me.

**Comment by RajuSPR** [comment]
How can I pass the following three parameters to CallApi method (stop_type, timeout, timeout_action)? 

I had passed the one argument stop_type to "soft". I get the response as follows
"{\n   \"error\" : {\n      \"error_code\" : \"UNKNOWN_ATTRIBUTE\",\n      \"error_message\" : \"The request body contains an unknown attribute stop_type.\"\n   }\n}\n"..

Below screenshots are for reference.

![image](https://user-images.githubusercontent.com/48589501/54528581-68e75a00-49a3-11e9-870a-3cb80eb2a43c.png)


![image](https://user-images.githubusercontent.com/48589501/54527850-2c1a6380-49a1-11e9-939f-97b96864d340.png)
![image](https://user-images.githubusercontent.com/48589501/54527859-389ebc00-49a1-11e9-8a30-cacb3cd0760d.png)
![image](https://user-images.githubusercontent.com/48589501/54527953-7865a380-49a1-11e9-9d71-ec010e813967.png)

Guide me please....!, How can I pass the parameters to the CallApi method?.

**Comment by Darep** [comment]
I noticed that in the API docs as well! I asked about and it's a mistake, so we will remove that "without timeout" -row from the API documentation

We will also fix the documentation in this repo.

Could you show a screenshot of your code please?

**Comment by RajuSPR** [comment]
Yeah sure...! 

1. restart Method

![image](https://user-images.githubusercontent.com/48589501/54581551-35541080-4a33-11e9-95a7-70b32c8b3f4a.png)

I only used the above-mentioned code. Otherwise, I had included the Upcloud-c-sharp-api files.  

Please check the below restart server functionality working or not. If it's working correctly, It must be to work for me.

![image](https://user-images.githubusercontent.com/48589501/54582237-02f7e280-4a36-11e9-986a-aa253b1e0a08.png)

This method throw the following issues. These are listed below

1. {"Error calling RestartServer: {\n   \"error\" : {\n      \"error_code\" : \"AUTHENTICATION_REQUIRED\",\n      \"error_message\" : \"The use of this API requires authentication. Create your account at https://www.upcloud.com/.\"\n   }\n}\n"}

After gave the authorization, it's throwing the new issue.

2. {"Error calling RestartServer: {\n   \"error\" : {\n      \"error_code\" : \"UNKNOWN_ATTRIBUTE\",\n      \"error_message\" : \"The request body contains an unknown attribute stop_type.\"\n   }\n}\n"}

I had set the default stop_type value as to false. 

![image](https://user-images.githubusercontent.com/48589501/54583717-10639b80-4a3b-11e9-8d14-4d99fbf5e55c.png)

After I'm getting the following issue. 

3. {"Error calling RestartServer: {\n   \"error\" : {\n      \"error_code\" : \"UNKNOWN_ATTRIBUTE\",\n      \"error_message\" : \"The request body contains an unknown attribute timeout.\"\n   }\n}\n"}


Thanks........!

**Comment by Darep** [comment]
Can you try changing the `new RestartServer();` to something like this?

```
            var restartServer = new RestartServer(StopTypeEnum.Soft, 30, TimeoutActionEnum.Destroy);
```

This should set the restart timeout to 30 seconds and force a hard restart in case the soft restart fails :)

**Comment by RajuSPR** [comment]
Now I had tried your way. But this also failed. The following error occurred.

"{\n   \"error\" : {\n      \"error_code\" : \"UNKNOWN_ATTRIBUTE\",\n      \"error_message\" : \"The request body contains an unknown attribute stop_type.\"\n   }\n}\n"

**Comment by Darep** [comment]
Ahh, yes, sorry, I think I understand now! :) The RestartServerHttpInfo is missing the authorization code, and after that, it gives the unknown attribute error. I will look into this bug and get back to you!

**Comment by RajuSPR** [comment]
Thanks.........! 

I'm waiting for your valuable response.....

**Comment by Darep** [comment]
Alright, I have now pushed a quick fix for the server restart! You can see the changes here: https://github.com/UpCloudLtd/upcloud-c-sharp-api/commit/3598ce6d6f1f1fd0d0e488dba21eebc4df295236

Please update your copy of the code and let us know if it works now. Note that the restart request finishes quickly and then the actual server restart takes some time.

**Comment by RajuSPR** [comment]
Thanks..

I had update the changes on my code.  Still, I'm facing the same issue.

![image](https://user-images.githubusercontent.com/48589501/54603186-b201e180-4a69-11e9-9803-c418b1772cd9.png)

**Comment by Darep** [comment]
Ah, sorry, you still need to supply the timeout, like so:

```
var restartServer = new RestartServer(RestartServer.StopTypeEnum.Soft, 30, RestartServer.TimeoutActionEnum.Destroy);
```

Or did you do that? If you did, then there's probably some bug in my fix 🤔

**Comment by RajuSPR** [comment]
Thank you so much @Darep 

Now, It's working fine.......!

Once again thanks for your support......

**Comment by Darep** [comment]
That's fantastic to hear! And thanks to you also for reporting this so we could get this fixed for everyone!
